// ============================================================================
// P6 — secure document delivery, against the real database and object store.
// ----------------------------------------------------------------------------
// The claim under test is narrow and absolute: an investor can obtain the bytes
// of a document if and only if the database says they may, and the only thing
// that ever leaves the server is a sixty-second signed URL.
//
// Every case below goes through the same public entry point the delivery route
// uses — issueDocumentDownload(authUserId, documentId) — so nothing is asserted
// against a private helper that the real request path could bypass. Objects are
// genuinely uploaded and genuinely fetched, so an expiry or a signature is a
// real HTTP outcome rather than a mocked one.
//
// Self-contained fixture (its own opportunities, investor organisations,
// contacts, Auth users and stored objects); nothing seeded is touched.
// ============================================================================
import { describe, it, expect, beforeAll } from "vitest";
import { adminQuery, type Session } from "@/lib/db/client";
import { createSupabaseAdminClient, ensureAuthUser } from "@/lib/supabase/admin";
import { DEMO_PASSWORD } from "@/lib/db/seed";
import { createOpportunity } from "@/lib/data/opportunities";
import {
  createInvestorOrganization, createInvestorContact, updateInvestorContact,
  updateInvestorOrganization, createPublicationFromOpportunity, updateDraftVersion,
  publishVersion, addPublicationDocument, removePublicationDocument,
  grantEntitlement, revokeEntitlement, supersedeActiveVersion, listEntitlements,
} from "@/lib/data/investor-portal";
import { loadPortalDocuments } from "@/lib/data/portal-feed";
import { issueDocumentDownload } from "@/lib/documents/secure-delivery";
import {
  DOCUMENT_BUCKET, SIGNED_URL_TTL_SECONDS, MAX_DOCUMENT_BYTES,
  checkUpload, newObjectPath, putDocumentObject, ensureDocumentBucket, signDocumentObject,
} from "@/lib/documents/storage";
import { adminSession, orgIdByName, orgUserSession, profileIdByEmail } from "./helpers";

const STANDARD = "standard@p6-docs.example";
const DILIGENCE = "diligence@p6-docs.example";
const DORMANT = "dormant@p6-docs.example";
const SUSPENDED = "principal@p6-suspended.example";

let staff: Session;
let adminUserId: string;

let standardOrgId: string;
let diligenceOrgId: string;
let suspendedOrgId: string;
let standardUid: string;
let diligenceUid: string;
let dormantUid: string;
let suspendedUid: string;
let dormantContactId: string;

let versionId: string;
let publicationId: string;
let withdrawnDocId: string;
let withdrawnPublicationId: string;

/** The three tiers of document on the main publication. */
let docs: { standard: string; diligence: string; internal: string };
/** What each document's object actually contains, to prove the right bytes flow. */
const BODIES: Record<string, string> = {};

/**
 * Attach a document to a draft version WITH a real object behind it: the path is
 * generated by the server exactly as the admin upload action generates it.
 */
async function attach(
  version: string, title: string, accessLevel: "standard" | "diligence" | "internal",
  body: string,
): Promise<string> {
  const mimeType = "application/pdf";
  const storagePath = newObjectPath(version, mimeType);
  const bytes = Buffer.from(body, "utf8");
  await putDocumentObject(storagePath, bytes, mimeType);
  const documentId = await addPublicationDocument(adminSession, {
    versionId: version, title, category: "other", storagePath,
    fileName: `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`,
    mimeType, sizeBytes: bytes.length, accessLevel,
  }, adminUserId);
  BODIES[documentId] = body;
  return documentId;
}

/** Create an internal opportunity + publication and return its draft version. */
async function draft(name: string): Promise<{ publicationId: string; versionId: string }> {
  const opportunityId = await createOpportunity(staff, {
    orgId: await orgIdByName("Meiji Shipping"),
    name, city: "Tokyo", country: "Japan", market: "Tokyo",
    assetType: "office", strategy: "core_plus", currency: "JPY",
    targetPrice: 4_000_000_000, niy: 3.8, targetIrr: 12,
    summary: `${name} — internal summary.`,
  });
  const created = await createPublicationFromOpportunity(adminSession, opportunityId, adminUserId);
  await updateDraftVersion(adminSession, created.versionId, {
    headline: `${name} headline`, highlights: ["A point"],
  });
  return created;
}

/** Fetch a signed URL and report what the object store actually answered. */
async function fetchSigned(signedUrl: string): Promise<{ status: number; body: string }> {
  const response = await fetch(signedUrl);
  return { status: response.status, body: response.ok ? await response.text() : "" };
}

async function downloadEventCount(documentId: string): Promise<number> {
  const rows = await adminQuery<{ n: string }>(
    `select count(*)::text as n from investor_activity_events
      where document_id = $1 and event_type = 'document_downloaded'`, [documentId]);
  return Number(rows[0].n);
}

beforeAll(async () => {
  staff = orgUserSession([await orgIdByName("Meiji Shipping")]);
  adminUserId = await profileIdByEmail("admin@reiwa.com");
  await ensureDocumentBucket();

  const supabase = createSupabaseAdminClient();
  standardUid = await ensureAuthUser(supabase,
    { email: STANDARD, password: DEMO_PASSWORD, name: "S. Fixture" });
  diligenceUid = await ensureAuthUser(supabase,
    { email: DILIGENCE, password: DEMO_PASSWORD, name: "D. Fixture" });
  dormantUid = await ensureAuthUser(supabase,
    { email: DORMANT, password: DEMO_PASSWORD, name: "Z. Dormant" });
  suspendedUid = await ensureAuthUser(supabase,
    { email: SUSPENDED, password: DEMO_PASSWORD, name: "X. Suspended" });

  standardOrgId = await createInvestorOrganization(adminSession, {
    name: "P6 Standard Partners", notes: "Created by tests/document-delivery.test.ts.",
  });
  diligenceOrgId = await createInvestorOrganization(adminSession, {
    name: "P6 Diligence House", notes: "Created by tests/document-delivery.test.ts.",
  });
  suspendedOrgId = await createInvestorOrganization(adminSession, {
    name: "P6 Suspended Trust", notes: "Created by tests/document-delivery.test.ts.",
  });

  await createInvestorContact(adminSession, {
    investorOrgId: standardOrgId, email: STANDARD, name: "S. Fixture", authUserId: standardUid,
  });
  await createInvestorContact(adminSession, {
    investorOrgId: diligenceOrgId, email: DILIGENCE, name: "D. Fixture", authUserId: diligenceUid,
  });
  dormantContactId = await createInvestorContact(adminSession, {
    investorOrgId: standardOrgId, email: DORMANT, name: "Z. Dormant", authUserId: dormantUid,
  });
  await createInvestorContact(adminSession, {
    investorOrgId: suspendedOrgId, email: SUSPENDED, name: "X. Suspended", authUserId: suspendedUid,
  });

  // ---- The publication under test -----------------------------------------
  const main = await draft("P6 Document Tower");
  publicationId = main.publicationId;
  versionId = main.versionId;
  docs = {
    standard: await attach(versionId, "P6 Teaser", "standard", "STANDARD-TIER-BYTES"),
    diligence: await attach(versionId, "P6 Data Room", "diligence", "DILIGENCE-TIER-BYTES"),
    internal: await attach(versionId, "P6 Internal IC Memo", "internal", "INTERNAL-ONLY-BYTES"),
  };
  await publishVersion(adminSession, versionId, adminUserId);

  // A second publication, entitled and then withdrawn.
  const withdrawn = await draft("P6 Withdrawn Wharf");
  withdrawnPublicationId = withdrawn.publicationId;
  withdrawnDocId = await attach(withdrawn.versionId, "P6 Withdrawn Teaser", "standard",
    "WITHDRAWN-BYTES");
  await publishVersion(adminSession, withdrawn.versionId, adminUserId);

  // ---- Entitlements --------------------------------------------------------
  for (const org of [standardOrgId, suspendedOrgId]) {
    await grantEntitlement(adminSession, {
      investorOrgId: org, publicationId, isVisible: true,
      placement: "featured", documentAccessLevel: "standard",
    }, adminUserId);
  }
  await grantEntitlement(adminSession, {
    investorOrgId: diligenceOrgId, publicationId, isVisible: true,
    placement: "featured", documentAccessLevel: "diligence",
  }, adminUserId);
  await grantEntitlement(adminSession, {
    investorOrgId: standardOrgId, publicationId: withdrawnPublicationId, isVisible: true,
    placement: "secondary", documentAccessLevel: "standard",
  }, adminUserId);

  // The suspended organisation is entitled BEFORE it is suspended, so what the
  // test proves is the suspension blocking access, not a missing entitlement.
  await updateInvestorOrganization(adminSession, suspendedOrgId, { status: "suspended" });
  await updateInvestorContact(adminSession, dormantContactId, { isActive: false });
  await supersedeActiveVersion(adminSession, withdrawnPublicationId);
});

// ============================================================================
describe("The private document store", () => {
  it("keeps the bucket private, so no object has a public URL", async () => {
    const { isPublic } = await ensureDocumentBucket();
    expect(isPublic).toBe(false);
  });

  it("refuses a public-object URL even when the object exists", async () => {
    const rows = await adminQuery<{ storage_path: string }>(
      "select storage_path from publication_documents where document_id = $1", [docs.standard]);
    const publicUrl =
      `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/` +
      `${DOCUMENT_BUCKET}/${rows[0].storage_path}`;
    const response = await fetch(publicUrl);
    expect(response.ok).toBe(false);
  });

  it("generates a random object path that borrows nothing from the file name", () => {
    const a = newObjectPath(versionId, "application/pdf");
    const b = newObjectPath(versionId, "application/pdf");
    expect(a).not.toEqual(b);
    expect(a.startsWith(`publications/${versionId}/`)).toBe(true);
    expect(a.endsWith(".pdf")).toBe(true);
    // The random segment is a UUID, so nothing about it is guessable.
    const segment = a.slice(`publications/${versionId}/`.length, -".pdf".length);
    expect(segment).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
  });

  it("validates the type and the size of an upload before storing it", () => {
    expect(checkUpload("application/pdf", 1024).ok).toBe(true);
    expect(checkUpload("application/pdf; charset=binary", 1024).ok).toBe(true);
    expect(checkUpload("APPLICATION/PDF", 1024).ok).toBe(true);

    expect(checkUpload("application/x-msdownload", 1024).ok).toBe(false);
    expect(checkUpload("text/html", 1024).ok).toBe(false);
    expect(checkUpload("", 1024).ok).toBe(false);
    expect(checkUpload("application/pdf", 0).ok).toBe(false);
    expect(checkUpload("application/pdf", MAX_DOCUMENT_BYTES + 1).ok).toBe(false);
    expect(checkUpload("application/pdf", MAX_DOCUMENT_BYTES).ok).toBe(true);
  });

  it("never lets a prototype key masquerade as an allowed type", () => {
    expect(checkUpload("constructor", 1024).ok).toBe(false);
    expect(checkUpload("__proto__", 1024).ok).toBe(false);
  });
});

// ============================================================================
describe("Tiered delivery", () => {
  it("delivers a standard document to a standard entitlement", async () => {
    const grant = await issueDocumentDownload(standardUid, docs.standard);
    expect(grant).not.toBeNull();
    const fetched = await fetchSigned(grant!.signedUrl);
    expect(fetched.status).toBe(200);
    expect(fetched.body).toBe(BODIES[docs.standard]);
  });

  it("refuses a diligence document to a standard entitlement", async () => {
    expect(await issueDocumentDownload(standardUid, docs.diligence)).toBeNull();
  });

  it("delivers both standard and diligence documents to a diligence entitlement", async () => {
    const standard = await issueDocumentDownload(diligenceUid, docs.standard);
    const diligence = await issueDocumentDownload(diligenceUid, docs.diligence);
    expect(standard).not.toBeNull();
    expect(diligence).not.toBeNull();
    expect((await fetchSigned(diligence!.signedUrl)).body).toBe(BODIES[docs.diligence]);
  });

  it("refuses an internal document at every tier", async () => {
    expect(await issueDocumentDownload(standardUid, docs.internal)).toBeNull();
    expect(await issueDocumentDownload(diligenceUid, docs.internal)).toBeNull();
  });

  it("never lists an internal document to an investor either", async () => {
    const listed = await loadPortalDocuments(diligenceUid, versionId);
    expect(listed.map((d) => d.title)).not.toContain("P6 Internal IC Memo");
    expect(listed.some((d) => (d as unknown as Record<string, unknown>).storagePath !== undefined))
      .toBe(false);
  });

  it("hands the investor no storage path in the document projection", async () => {
    const listed = await loadPortalDocuments(standardUid, versionId);
    expect(listed.length).toBeGreaterThan(0);
    for (const document of listed) {
      expect(Object.keys(document)).toEqual(
        expect.not.arrayContaining(["storagePath", "storage_path"]));
      expect(JSON.stringify(document)).not.toContain("publications/");
    }
  });
});

// ============================================================================
describe("Signed URLs", () => {
  // --------------------------------------------------------------------------
  // A signed-URL token has two shapes, and these tests must hold for both.
  //
  //   hosted Supabase  a JWT: `header.payload.signature`, expiry in the
  //                    payload's `exp` claim.
  //   local stand-in   `<exp>.<signature>`, expiry in the first segment.
  //
  // The earlier version of these helpers understood only the stand-in. Against
  // hosted Supabase `Number(token.split(".")[0])` is NaN, and a tamper written
  // as a regex on `token=(\d+)\.` matched nothing at all — so the "tampered"
  // request was the ORIGINAL VALID URL, and the test failed while claiming a
  // security property it had never exercised. Hence `expect(tampered).not
  // .toBe(token)` below: a tamper that silently does nothing must fail loudly
  // rather than quietly assert nothing.
  // --------------------------------------------------------------------------
  const isJwt = (token: string): boolean => token.split(".").length === 3;

  const jwtPayload = (token: string): { exp: number } =>
    JSON.parse(Buffer.from(token.split(".")[1], "base64url").toString("utf8"));

  /** The expiry the token claims, in epoch seconds, whichever shape it is. */
  const tokenExpiry = (token: string): number =>
    isJwt(token) ? Number(jwtPayload(token).exp) : Number(token.split(".")[0]);

  /** The same token with its signature altered and nothing else changed. */
  const tamperSignature = (token: string): string => {
    const parts = token.split(".");
    const i = isJwt(token) ? 2 : 1;
    parts[i] = (parts[i][0] === "a" ? "b" : "a") + parts[i].slice(1);
    return parts.join(".");
  };

  /** The same token claiming a different expiry, carrying its original signature. */
  const tamperExpiry = (token: string, expiresAt: number): string => {
    const parts = token.split(".");
    if (!isJwt(token)) return `${expiresAt}.${parts[1]}`;
    parts[1] = Buffer.from(JSON.stringify({ ...jwtPayload(token), exp: expiresAt }))
      .toString("base64url");
    return parts.join(".");
  };

  const tokenOf = (signedUrl: string): string =>
    new URL(signedUrl).searchParams.get("token") ?? "";

  const withToken = (signedUrl: string, token: string): string => {
    const url = new URL(signedUrl);
    url.searchParams.set("token", token);
    return url.toString();
  };

  it("expires in sixty seconds", async () => {
    expect(SIGNED_URL_TTL_SECONDS).toBe(60);
    const grant = await issueDocumentDownload(standardUid, docs.standard);
    const token = tokenOf(grant!.signedUrl);
    const ttl = tokenExpiry(token) - Math.floor(Date.now() / 1000);
    expect(Number.isFinite(ttl)).toBe(true);
    expect(ttl).toBeGreaterThan(0);
    expect(ttl).toBeLessThanOrEqual(SIGNED_URL_TTL_SECONDS);
  });

  it("is fetchable while it is still valid", async () => {
    const grant = await issueDocumentDownload(standardUid, docs.standard);
    const response = await fetch(grant!.signedUrl);
    expect(response.ok).toBe(true);
  });

  it("refuses a URL whose signature has been tampered with", async () => {
    const grant = await issueDocumentDownload(standardUid, docs.standard);
    const token = tokenOf(grant!.signedUrl);
    const tampered = tamperSignature(token);
    expect(tampered).not.toBe(token); // the tamper must actually change something
    const response = await fetch(withToken(grant!.signedUrl, tampered));
    expect(response.ok).toBe(false);
  });

  it("refuses a URL whose expiry has been pushed into the future", async () => {
    const grant = await issueDocumentDownload(standardUid, docs.standard);
    const token = tokenOf(grant!.signedUrl);
    const tampered = tamperExpiry(token, Math.floor(Date.now() / 1000) + 86_400);
    expect(tampered).not.toBe(token);
    expect(tokenExpiry(tampered)).toBeGreaterThan(tokenExpiry(token));
    const response = await fetch(withToken(grant!.signedUrl, tampered));
    expect(response.ok).toBe(false);
  });

  it("refuses an already-expired URL", async () => {
    const rows = await adminQuery<{ storage_path: string }>(
      "select storage_path from publication_documents where document_id = $1", [docs.standard]);
    // Sign for a moment that has already passed, then present it.
    const signed = await signDocumentObject(rows[0].storage_path);
    expect(signed).not.toBeNull();
    const token = tokenOf(signed!);
    const expired = tamperExpiry(token, 0);
    expect(expired).not.toBe(token);
    const response = await fetch(withToken(signed!, expired));
    expect(response.ok).toBe(false);
  });
});

// ============================================================================
describe("Refusals", () => {
  it("refuses a document id that does not exist", async () => {
    expect(await issueDocumentDownload(
      standardUid, "00000000-0000-4000-8000-000000000000")).toBeNull();
  });

  it("refuses a malformed document id without erroring", async () => {
    for (const id of ["../../etc/passwd", "not-a-uuid", "", "'; drop table x; --"]) {
      expect(await issueDocumentDownload(standardUid, id)).toBeNull();
    }
  });

  it("refuses a document belonging to a publication this investor is not entitled to", async () => {
    // The diligence org holds no entitlement to the withdrawn publication.
    expect(await issueDocumentDownload(diligenceUid, withdrawnDocId)).toBeNull();
  });

  it("refuses a withdrawn publication's document to an entitled investor", async () => {
    expect(await issueDocumentDownload(standardUid, withdrawnDocId)).toBeNull();
  });

  it("refuses a deactivated contact", async () => {
    expect(await issueDocumentDownload(dormantUid, docs.standard)).toBeNull();
  });

  it("refuses a contact of a suspended organisation", async () => {
    expect(await issueDocumentDownload(suspendedUid, docs.standard)).toBeNull();
  });

  it("refuses an unknown Auth user", async () => {
    expect(await issueDocumentDownload(
      "11111111-2222-4333-8444-555555555555", docs.standard)).toBeNull();
  });

  it("stops issuing new URLs the moment an entitlement is revoked", async () => {
    const contactOrg = await createInvestorOrganization(adminSession, {
      name: "P6 Revocable Partners", notes: "Created by tests/document-delivery.test.ts.",
    });
    const supabase = createSupabaseAdminClient();
    const uid = await ensureAuthUser(supabase,
      { email: "revoke@p6-docs.example", password: DEMO_PASSWORD, name: "R. Fixture" });
    await createInvestorContact(adminSession, {
      investorOrgId: contactOrg, email: "revoke@p6-docs.example", name: "R. Fixture",
      authUserId: uid,
    });
    await grantEntitlement(adminSession, {
      investorOrgId: contactOrg, publicationId, isVisible: true,
      placement: "featured", documentAccessLevel: "standard",
    }, adminUserId);

    expect(await issueDocumentDownload(uid, docs.standard)).not.toBeNull();

    const entitlements = await listEntitlements(adminSession, contactOrg);
    const mine = entitlements.find((e) => e.publicationId === publicationId)!;
    await revokeEntitlement(adminSession, mine.entitlementId);

    // No cache, no grace period: the very next request is refused.
    expect(await issueDocumentDownload(uid, docs.standard)).toBeNull();
  });
});

// ============================================================================
describe("The activity trail", () => {
  it("records document_downloaded only after an authorised delivery", async () => {
    const before = await downloadEventCount(docs.diligence);
    const grant = await issueDocumentDownload(diligenceUid, docs.diligence);
    expect(grant).not.toBeNull();
    expect(await downloadEventCount(docs.diligence)).toBe(before + 1);
  });

  it("records the publication and version the document belonged to", async () => {
    await issueDocumentDownload(standardUid, docs.standard);
    const rows = await adminQuery<{ publication_id: string; version_id: string }>(
      `select publication_id, version_id from investor_activity_events
        where document_id = $1 and event_type = 'document_downloaded'
        order by occurred_at desc limit 1`, [docs.standard]);
    expect(rows[0].publication_id).toBe(publicationId);
    expect(rows[0].version_id).toBe(versionId);
  });

  it("records nothing when a download is refused", async () => {
    const before = await downloadEventCount(docs.internal);
    await issueDocumentDownload(standardUid, docs.internal);
    await issueDocumentDownload(diligenceUid, docs.internal);
    await issueDocumentDownload(dormantUid, docs.standard);
    await issueDocumentDownload(suspendedUid, docs.standard);
    expect(await downloadEventCount(docs.internal)).toBe(before);
    // A refused standard download adds nothing on behalf of the refused contact.
    const rows = await adminQuery<{ n: string }>(
      `select count(*)::text as n from investor_activity_events e
         join investor_contacts c on c.investor_contact_id = e.investor_contact_id
        where e.event_type = 'document_downloaded'
          and lower(c.email) in ($1, $2)`, [DORMANT, SUSPENDED]);
    expect(Number(rows[0].n)).toBe(0);
  });
});

// ============================================================================
describe("Removing a document", () => {
  it("deletes the stored object along with the row", async () => {
    const version = (await draft("P6 Disposable Court")).versionId;
    const documentId = await attach(version, "P6 Disposable", "standard", "DISPOSABLE-BYTES");
    const before = await adminQuery<{ storage_path: string }>(
      "select storage_path from publication_documents where document_id = $1", [documentId]);
    const storagePath = before[0].storage_path;
    expect(await signDocumentObject(storagePath)).not.toBeNull();

    const returned = await removePublicationDocument(adminSession, documentId);
    expect(returned).toBe(storagePath);

    const { deleteDocumentObject } = await import("@/lib/documents/storage");
    await deleteDocumentObject(returned!);

    // The object is gone, so nothing can be signed for it any more, and the row
    // that was the only record of its location is gone with it.
    expect(await signDocumentObject(storagePath)).toBeNull();
    const remaining = await adminQuery<{ n: string }>(
      "select count(*)::text as n from publication_documents where document_id = $1", [documentId]);
    expect(Number(remaining[0].n)).toBe(0);
  });

  it("reports nothing to remove when the row was already gone", async () => {
    expect(await removePublicationDocument(
      adminSession, "00000000-0000-4000-8000-000000000001")).toBeNull();
  });
});
