import type { OpportunityDocument } from "@/lib/data/opportunity-documents";
import type { DdItemRecord } from "@/lib/data/due-diligence";
import { DOC_CATEGORY_KEYS } from "@/lib/documents/catalog";
import { MAX_DOCUMENT_BYTES, UPLOAD_ACCEPT } from "@/lib/documents/constraints";
import { uploadDocumentAction } from "@/app/actions/workspace";
import { formatDate } from "@/lib/format";
import { Badge } from "@/components/ui/badge";
import { Section, TableWrap, Th, Td, Empty, Provenance } from "@/components/workspace/primitives";

/**
 * Internal opportunity documents.
 *
 * The same private bucket, the same tiers and the same short-lived signed-URL
 * delivery as everything else — this section adds a relationship, not a second
 * storage system. Internal documents are `internal` by default and are NOT
 * investor-visible: what an investor sees is controlled entirely by the
 * publication's own document list, which is a separate, deliberate act.
 *
 * Upload goes through the existing secure path and nothing else: the file is
 * validated against what the server received, stored at a random
 * server-generated object path, and only then recorded. The browser never
 * supplies or receives a storage path, and a document is opened by presenting
 * its id to the delivery route, which signs it for sixty seconds after the
 * database has agreed.
 */
export function DocumentsSection({
  opportunityId, documents, ddItems, canWrite,
}: {
  opportunityId: string;
  documents: OpportunityDocument[];
  ddItems: DdItemRecord[];
  canWrite: boolean;
}) {
  const linkedByDoc = new Map<string, DdItemRecord[]>();
  for (const it of ddItems) {
    if (!it.sourceDocumentId) continue;
    const list = linkedByDoc.get(it.sourceDocumentId) ?? [];
    list.push(it);
    linkedByDoc.set(it.sourceDocumentId, list);
  }

  return (
    <div>
      <Section eyebrow="Vault" title={`Internal documents (${documents.length})`}>
        {documents.length === 0 ? (
          <Empty
            title="No documents recorded against this opportunity."
            hint="Documents are categorised so a finding can be traced back to the file it came from."
          />
        ) : (
          <TableWrap>
            <table className="w-full border-collapse">
              <thead>
                <tr>
                  <Th>Title</Th>
                  <Th>File</Th>
                  <Th>Category</Th>
                  <Th>Linked diligence</Th>
                  <Th>Access</Th>
                  <Th>Added</Th>
                </tr>
              </thead>
              <tbody>
                {documents.map((d) => {
                  const linked = linkedByDoc.get(d.documentId) ?? [];
                  return (
                    <tr key={d.documentId}>
                      <Td>
                        {/* The id, never the storage path. The route signs it. */}
                        <a href={`/opportunities/${opportunityId}/documents/${d.documentId}`}
                          rel="noreferrer"
                          className="underline decoration-line underline-offset-2 hover:text-ink">
                          {d.title}
                        </a>
                      </Td>
                      <Td className="text-xs text-ink-muted">{d.fileName ?? "—"}</Td>
                      <Td className="text-xs text-ink-muted">{d.category}</Td>
                      <Td className="text-xs text-ink-muted">
                        {linked.length === 0
                          ? "—"
                          : linked.map((l) => l.item).join(", ")}
                      </Td>
                      <Td>
                        <Badge tone={d.accessLevel === "internal" ? "muted" : "caution"}>
                          {d.accessLevel}
                        </Badge>
                      </Td>
                      <Td className="text-2xs text-ink-faint">
                        {formatDate(d.createdAt)}
                        {d.uploadedByName ? ` · ${d.uploadedByName}` : ""}
                      </Td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </TableWrap>
        )}
        <Provenance>
          Internal documents are never exposed to investors by being recorded here.
          An investor sees only what a publication version explicitly carries.
        </Provenance>
      </Section>

      {canWrite && (
        <Section eyebrow="Upload" title="Add a document">
          <p className="mb-4 max-w-2xl text-xs leading-relaxed text-ink-muted">
            The file is stored in the same private bucket as everything else, at
            a path generated by the server, and is served only as a
            sixty-second signed URL. Files are capped
            at {Math.round(MAX_DOCUMENT_BYTES / 1024 / 1024)}MB and the type is
            checked against what the server receives.
          </p>
          <form action={uploadDocumentAction.bind(null, opportunityId)}
            className="max-w-3xl space-y-3">
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <label className="block">
                <span className="eyebrow">Title</span>
                <input name="title" required
                  className="mt-1 h-9 w-full rounded border border-line bg-surface-card px-3 text-sm text-ink focus:border-line-strong focus:outline-none" />
              </label>
              <label className="block">
                <span className="eyebrow">Category</span>
                <select name="category" defaultValue="Technical DD"
                  className="mt-1 h-9 w-full rounded border border-line bg-surface-card px-2 text-sm text-ink focus:border-line-strong focus:outline-none">
                  {DOC_CATEGORY_KEYS.map((c) => <option key={c} value={c}>{c}</option>)}
                </select>
              </label>
            </div>
            <label className="block">
              <span className="eyebrow">File</span>
              <input name="file" type="file" required accept={UPLOAD_ACCEPT}
                className="mt-1 block w-full text-xs text-ink-muted file:mr-3 file:rounded file:border file:border-line file:bg-surface-card file:px-3 file:py-1.5 file:text-xs file:font-medium file:text-ink-muted hover:file:text-ink" />
            </label>
            <button type="submit"
              className="rounded bg-purple px-3.5 py-2 text-xs font-semibold text-surface hover:bg-purple-70">
              Upload document
            </button>
          </form>
        </Section>
      )}
    </div>
  );
}
